# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_localized', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
            ],
        ),
    ]
